name: Update GitHub Projects

on:
    schedule:
        # Run every Sunday at 2 AM UTC
        - cron: "0 2 * * 0"
    workflow_dispatch: # Allow manual triggering
    push:
        paths:
            - "scripts/**"
            - ".github/workflows/update-projects.yml"

jobs:
    update-projects:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  cd scripts
                  pip install -r requirements.txt

            - name: Update project files
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  cd scripts
                  python analyze_repos.py \
                    --username rl337 \
                    --output ../docs/_projects \
                    --token $GITHUB_TOKEN

            - name: Check for changes
              id: verify-changed-files
              run: |
                  if [ -n "$(git status --porcelain)" ]; then
                    echo "changed=true" >> $GITHUB_OUTPUT
                  else
                    echo "changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Commit and push changes
              if: steps.verify-changed-files.outputs.changed == 'true'
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add docs/_projects/
                  git commit -m "🤖 Auto-update project files from GitHub repos

                  - Updated project analysis and activity levels
                  - Generated from GitHub API data
                  - Automated by GitHub Actions workflow"
                  git push

            - name: Comment on commit
              if: steps.verify-changed-files.outputs.changed == 'true'
              run: |
                  echo "✅ Project files updated successfully!"
                  echo "📊 Check the projects page to see the latest repository analysis."
