name: Validation Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t rl337-dev .

      - name: Run comprehensive validation in Docker
        run: |
          chmod +x run_checks.sh
          echo "🐳 Running Docker command..."
          echo "🐳 Testing Docker container..."
          docker run --rm rl337-dev echo "🐳 Docker container is working!"
          echo "🐳 Running validation in Docker..."
          docker run --rm \
            -v "$(pwd)":/workspace \
            -w /workspace \
            -e DOCKER_CONTAINER=true \
            rl337-dev \
            /bin/bash -c "echo '🐳 Inside Docker container' && echo 'DOCKER_CONTAINER='$DOCKER_CONTAINER && ./run_checks.sh"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: validation-results
          path: |
            scripts/coverage.xml
            scripts/htmlcov/
          retention-days: 7

    # Note: PR commenting removed due to GITHUB_TOKEN permissions
    # The validation results are visible in the Actions tab

  jekyll-build:
    runs-on: ubuntu-latest
    needs: validation

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t rl337-dev .

      - name: Build Jekyll site in Docker
        run: |
          docker run --rm \
            -v "$(pwd)":/workspace \
            -w /workspace \
            rl337-dev \
            bash -c "cd docs && bundle exec jekyll build --safe"

      - name: Upload site artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jekyll-site
          path: docs/_site/
          retention-days: 7
