name: Validation Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t rl337-dev .
        
    - name: Run comprehensive validation in Docker
      run: |
        chmod +x run_checks.sh docker-run.sh
        ./docker-run.sh ./run_checks.sh
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: validation-results
        path: |
          scripts/coverage.xml
          scripts/htmlcov/
        retention-days: 7
        
    - name: Comment PR with results
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // This would be enhanced to parse actual test results
          const comment = `## 🔍 Validation Results
          
          **Status:** ${process.env.VALIDATION_STATUS || 'Completed'}
          
          All validation checks have been run. Check the Actions tab for detailed results.
          
          ### Checks Performed:
          - ✅ Python syntax and linting
          - ✅ Jekyll build validation  
          - ✅ Shell script validation
          - ✅ YAML syntax validation
          - ✅ File structure validation
          - ✅ Security checks
          
          View full details in the [Actions tab](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

  jekyll-build:
    runs-on: ubuntu-latest
    needs: validation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t rl337-dev .
        
    - name: Build Jekyll site in Docker
      run: |
        chmod +x docker-run.sh
        ./docker-run.sh bash -c "cd docs && bundle exec jekyll build --safe"
        
    - name: Upload site artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jekyll-site
        path: docs/_site/
        retention-days: 7
